---
- hosts: all
  vars:
    - create_user_file: yes
    - user: clinton
  tasks:
    - name: create file for user
      file:
        path: /home/{{user}}/ myfile-2
        state: touch
      when: create_user_file
